fix: add missing .read() which caused AttributeError
  File "/home/ss/.local/share/virtualenvs/appimage-builder-7nkPsOzH/lib/python3.9/site-packages/appimagebuilder/app_dir/deploy/pacman/venv.py", line 125, in _run_pacman_list_packages_and_versions
    return output.stdout.decode("utf-8").splitlines()  # noqa:
AttributeError: '_io.BufferedReader' object has no attribute 'decode'